from django.http import HttpResponse

def docker(request):
    return HttpResponse("<h2>What is Docker?<h2/><h2> Docker makes development efficient and predicatable Docker takes away repetitive, mundane configuration tasks and is used throughout the development lifecycle for fast, easy and portable application development desktop and cloud.<h2/> <h2>Docker's comprehensive end to end platform includes UIs, CLIs, APIs and security that are engineered to work together across the entire application delivery lifecycle<h2/>") 
def build(request):
    return HttpResponse("<h2> Build <h2/>  <h2> # Get a head start on your coding by  leveraging Docker images to efficiently develop your own unique applications on Windows and Mac. Create your multi-container application using Docker Compose.<h2/> <h2># Integrate with your favorite tools throughout your development pipeline – Docker works with all development tools you use including VS Code, CircleCI and GitHub.<h2/><h2># Package applications as portable container images to run in any environment consistently from on-premises Kuberneters to AWS ECS, Azure ACI, Google GKE and more.<h2/>")
def share(request):
    return HttpResponse("<h2> Share<h2/> <h2> # Leverage Docker Trusted Content, including Docker OFficial Images and images from Docker Verified Publishers from the Docker Hub repositroy.<h2/> <h2> # Innovate by collaborating with team members and other developers and by easily publishing images to Docker Hub.<h2/> <h2> # Personalize developer access to images with roles based access control and get insights into activity history with Docker Hub Audit Logs.<h2/>") 
def run(request):
    return HttpResponse("<h2>RUN<h2/> <h2> # Deliver multiple applications hassle free and have them run the same way on all your environments including design, testing, staging and production - desktop or cloud -native.<h2/> <h2> # Deploy your applications in separate containers independently and in different languages. Reduce the risk of conflic between languages, libraries and frameworks.<h2/> <h2># Speed development with the simplicty of Docker Compose CLI and with one command, launch your aplications locally and on the cloud with AWS ECS and Azure ACI.<h2/>") 